### ISSUE TITLE
Uable to download pretrained model from the models folder ( LFS bandwidth)

### ISSUE THREAD

**Issue by wxyxy33** [srinidhiPY/ICCV-CDPATH2021-ID-8#2]
”ERROR  response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access“，I get an error when downloading a model，I'm wondering if there is a problem with permissions or the author's LFS capacity. If the problem is not solved, it will be difficult to reproduce the indicators mentioned in the author's paper.I hope you will get back to me soon，thank you.

**Comment by srinidhiPY** [comment]
Really sorry for the reply. Due to space constraints, I am unable to upload the pre-trained model to Github. However, you can download the same pretrained model from our previous repository: https://github.com/srinidhiPY/SSL_CR_Histo
